export default {
    "SDKVersion": "",
    "appId": "__UNI__5FD0E1C",
    "appLanguage": "zh-Hans",
    "appName": "喵客",
    "appVersion": "1.0.0",
    "appVersionCode": "100",
    "browserName": "safari",
    "browserVersion": "13.0.3",
    "deviceId": "16894283277418087879",
    "deviceModel": "iPhone",
    "deviceOrientation": "portrait",
    "devicePixelRatio": 2,
    "deviceType": "phone",
    "hostLanguage": "zh-CN",
    "hostName": "safari",
    "hostTheme": "light",
    "hostVersion": "13.0.3",
    "language": "zh-CN",
    "model": "iPhone",
    "osName": "ios",
    "osVersion": "13.2.3",
    "pixelRatio": 2,
    "platform": "ios",
    "safeArea": {
        "left": 0,
        "right": 414,
        "top": 0,
        "bottom": 896,
        "width": 414,
        "height": 896
    },
    "safeAreaInsets": {
        "top": 0,
        "right": 0,
        "bottom": 0,
        "left": 0
    },
    "screenHeight": 896,
    "screenWidth": 414,
    "statusBarHeight": 0,
    "system": "iOS 13.2.3",
    "ua": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",
    "uniCompileVersion": "3.8.7",
    "uniPlatform": "web",
    "uniRuntimeVersion": "3.8.7",
    "version": "",
    "windowBottom": 50,
    "windowHeight": 846,
    "windowTop": 0,
    "windowWidth": 414
}